// Code generated by ent, DO NOT EDIT.

package iderelease

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the iderelease type in the database.
	Label = "ide_release"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldMinAppVersion holds the string denoting the min_app_version field in the database.
	FieldMinAppVersion = "min_app_version"
	// FieldBinaries holds the string denoting the binaries field in the database.
	FieldBinaries = "binaries"
	// FieldReleaseNotes holds the string denoting the release_notes field in the database.
	FieldReleaseNotes = "release_notes"
	// FieldIsMandatory holds the string denoting the is_mandatory field in the database.
	FieldIsMandatory = "is_mandatory"
	// FieldIsLatest holds the string denoting the is_latest field in the database.
	FieldIsLatest = "is_latest"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// Table holds the table name of the iderelease in the database.
	Table = "ide_releases"
)

// Columns holds all SQL columns for iderelease fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldKind,
	FieldVersion,
	FieldMinAppVersion,
	FieldBinaries,
	FieldReleaseNotes,
	FieldIsMandatory,
	FieldIsLatest,
	FieldPublishedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// DefaultMinAppVersion holds the default value on creation for the "min_app_version" field.
	DefaultMinAppVersion string
	// MinAppVersionValidator is a validator for the "min_app_version" field. It is called by the builders before save.
	MinAppVersionValidator func(string) error
	// DefaultBinaries holds the default value on creation for the "binaries" field.
	DefaultBinaries func() map[string]map[string]interface{}
	// DefaultReleaseNotes holds the default value on creation for the "release_notes" field.
	DefaultReleaseNotes string
	// DefaultIsMandatory holds the default value on creation for the "is_mandatory" field.
	DefaultIsMandatory bool
	// DefaultIsLatest holds the default value on creation for the "is_latest" field.
	DefaultIsLatest bool
)

// OrderOption defines the ordering options for the IDERelease queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByMinAppVersion orders the results by the min_app_version field.
func ByMinAppVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinAppVersion, opts...).ToFunc()
}

// ByReleaseNotes orders the results by the release_notes field.
func ByReleaseNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseNotes, opts...).ToFunc()
}

// ByIsMandatory orders the results by the is_mandatory field.
func ByIsMandatory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsMandatory, opts...).ToFunc()
}

// ByIsLatest orders the results by the is_latest field.
func ByIsLatest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLatest, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}
