// Code generated by ent, DO NOT EDIT.

package iderelease

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldUpdatedAt, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldKind, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldVersion, v))
}

// MinAppVersion applies equality check predicate on the "min_app_version" field. It's identical to MinAppVersionEQ.
func MinAppVersion(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldMinAppVersion, v))
}

// ReleaseNotes applies equality check predicate on the "release_notes" field. It's identical to ReleaseNotesEQ.
func ReleaseNotes(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldReleaseNotes, v))
}

// IsMandatory applies equality check predicate on the "is_mandatory" field. It's identical to IsMandatoryEQ.
func IsMandatory(v bool) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldIsMandatory, v))
}

// IsLatest applies equality check predicate on the "is_latest" field. It's identical to IsLatestEQ.
func IsLatest(v bool) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldIsLatest, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldPublishedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLTE(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldContainsFold(FieldKind, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldContainsFold(FieldVersion, v))
}

// MinAppVersionEQ applies the EQ predicate on the "min_app_version" field.
func MinAppVersionEQ(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldMinAppVersion, v))
}

// MinAppVersionNEQ applies the NEQ predicate on the "min_app_version" field.
func MinAppVersionNEQ(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldMinAppVersion, v))
}

// MinAppVersionIn applies the In predicate on the "min_app_version" field.
func MinAppVersionIn(vs ...string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldIn(FieldMinAppVersion, vs...))
}

// MinAppVersionNotIn applies the NotIn predicate on the "min_app_version" field.
func MinAppVersionNotIn(vs ...string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNotIn(FieldMinAppVersion, vs...))
}

// MinAppVersionGT applies the GT predicate on the "min_app_version" field.
func MinAppVersionGT(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGT(FieldMinAppVersion, v))
}

// MinAppVersionGTE applies the GTE predicate on the "min_app_version" field.
func MinAppVersionGTE(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGTE(FieldMinAppVersion, v))
}

// MinAppVersionLT applies the LT predicate on the "min_app_version" field.
func MinAppVersionLT(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLT(FieldMinAppVersion, v))
}

// MinAppVersionLTE applies the LTE predicate on the "min_app_version" field.
func MinAppVersionLTE(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLTE(FieldMinAppVersion, v))
}

// MinAppVersionContains applies the Contains predicate on the "min_app_version" field.
func MinAppVersionContains(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldContains(FieldMinAppVersion, v))
}

// MinAppVersionHasPrefix applies the HasPrefix predicate on the "min_app_version" field.
func MinAppVersionHasPrefix(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldHasPrefix(FieldMinAppVersion, v))
}

// MinAppVersionHasSuffix applies the HasSuffix predicate on the "min_app_version" field.
func MinAppVersionHasSuffix(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldHasSuffix(FieldMinAppVersion, v))
}

// MinAppVersionEqualFold applies the EqualFold predicate on the "min_app_version" field.
func MinAppVersionEqualFold(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEqualFold(FieldMinAppVersion, v))
}

// MinAppVersionContainsFold applies the ContainsFold predicate on the "min_app_version" field.
func MinAppVersionContainsFold(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldContainsFold(FieldMinAppVersion, v))
}

// ReleaseNotesEQ applies the EQ predicate on the "release_notes" field.
func ReleaseNotesEQ(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldReleaseNotes, v))
}

// ReleaseNotesNEQ applies the NEQ predicate on the "release_notes" field.
func ReleaseNotesNEQ(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldReleaseNotes, v))
}

// ReleaseNotesIn applies the In predicate on the "release_notes" field.
func ReleaseNotesIn(vs ...string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldIn(FieldReleaseNotes, vs...))
}

// ReleaseNotesNotIn applies the NotIn predicate on the "release_notes" field.
func ReleaseNotesNotIn(vs ...string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNotIn(FieldReleaseNotes, vs...))
}

// ReleaseNotesGT applies the GT predicate on the "release_notes" field.
func ReleaseNotesGT(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGT(FieldReleaseNotes, v))
}

// ReleaseNotesGTE applies the GTE predicate on the "release_notes" field.
func ReleaseNotesGTE(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGTE(FieldReleaseNotes, v))
}

// ReleaseNotesLT applies the LT predicate on the "release_notes" field.
func ReleaseNotesLT(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLT(FieldReleaseNotes, v))
}

// ReleaseNotesLTE applies the LTE predicate on the "release_notes" field.
func ReleaseNotesLTE(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLTE(FieldReleaseNotes, v))
}

// ReleaseNotesContains applies the Contains predicate on the "release_notes" field.
func ReleaseNotesContains(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldContains(FieldReleaseNotes, v))
}

// ReleaseNotesHasPrefix applies the HasPrefix predicate on the "release_notes" field.
func ReleaseNotesHasPrefix(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldHasPrefix(FieldReleaseNotes, v))
}

// ReleaseNotesHasSuffix applies the HasSuffix predicate on the "release_notes" field.
func ReleaseNotesHasSuffix(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldHasSuffix(FieldReleaseNotes, v))
}

// ReleaseNotesEqualFold applies the EqualFold predicate on the "release_notes" field.
func ReleaseNotesEqualFold(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEqualFold(FieldReleaseNotes, v))
}

// ReleaseNotesContainsFold applies the ContainsFold predicate on the "release_notes" field.
func ReleaseNotesContainsFold(v string) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldContainsFold(FieldReleaseNotes, v))
}

// IsMandatoryEQ applies the EQ predicate on the "is_mandatory" field.
func IsMandatoryEQ(v bool) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldIsMandatory, v))
}

// IsMandatoryNEQ applies the NEQ predicate on the "is_mandatory" field.
func IsMandatoryNEQ(v bool) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldIsMandatory, v))
}

// IsLatestEQ applies the EQ predicate on the "is_latest" field.
func IsLatestEQ(v bool) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldIsLatest, v))
}

// IsLatestNEQ applies the NEQ predicate on the "is_latest" field.
func IsLatestNEQ(v bool) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldIsLatest, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.IDERelease {
	return predicate.IDERelease(sql.FieldLTE(FieldPublishedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IDERelease) predicate.IDERelease {
	return predicate.IDERelease(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IDERelease) predicate.IDERelease {
	return predicate.IDERelease(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IDERelease) predicate.IDERelease {
	return predicate.IDERelease(sql.NotPredicates(p))
}
