// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/iderelease"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// IDEReleaseUpdate is the builder for updating IDERelease entities.
type IDEReleaseUpdate struct {
	config
	hooks    []Hook
	mutation *IDEReleaseMutation
}

// Where appends a list predicates to the IDEReleaseUpdate builder.
func (_u *IDEReleaseUpdate) Where(ps ...predicate.IDERelease) *IDEReleaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IDEReleaseUpdate) SetUpdatedAt(v time.Time) *IDEReleaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *IDEReleaseUpdate) SetKind(v string) *IDEReleaseUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *IDEReleaseUpdate) SetNillableKind(v *string) *IDEReleaseUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *IDEReleaseUpdate) SetVersion(v string) *IDEReleaseUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *IDEReleaseUpdate) SetNillableVersion(v *string) *IDEReleaseUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetMinAppVersion sets the "min_app_version" field.
func (_u *IDEReleaseUpdate) SetMinAppVersion(v string) *IDEReleaseUpdate {
	_u.mutation.SetMinAppVersion(v)
	return _u
}

// SetNillableMinAppVersion sets the "min_app_version" field if the given value is not nil.
func (_u *IDEReleaseUpdate) SetNillableMinAppVersion(v *string) *IDEReleaseUpdate {
	if v != nil {
		_u.SetMinAppVersion(*v)
	}
	return _u
}

// SetBinaries sets the "binaries" field.
func (_u *IDEReleaseUpdate) SetBinaries(v map[string]map[string]interface{}) *IDEReleaseUpdate {
	_u.mutation.SetBinaries(v)
	return _u
}

// SetReleaseNotes sets the "release_notes" field.
func (_u *IDEReleaseUpdate) SetReleaseNotes(v string) *IDEReleaseUpdate {
	_u.mutation.SetReleaseNotes(v)
	return _u
}

// SetNillableReleaseNotes sets the "release_notes" field if the given value is not nil.
func (_u *IDEReleaseUpdate) SetNillableReleaseNotes(v *string) *IDEReleaseUpdate {
	if v != nil {
		_u.SetReleaseNotes(*v)
	}
	return _u
}

// SetIsMandatory sets the "is_mandatory" field.
func (_u *IDEReleaseUpdate) SetIsMandatory(v bool) *IDEReleaseUpdate {
	_u.mutation.SetIsMandatory(v)
	return _u
}

// SetNillableIsMandatory sets the "is_mandatory" field if the given value is not nil.
func (_u *IDEReleaseUpdate) SetNillableIsMandatory(v *bool) *IDEReleaseUpdate {
	if v != nil {
		_u.SetIsMandatory(*v)
	}
	return _u
}

// SetIsLatest sets the "is_latest" field.
func (_u *IDEReleaseUpdate) SetIsLatest(v bool) *IDEReleaseUpdate {
	_u.mutation.SetIsLatest(v)
	return _u
}

// SetNillableIsLatest sets the "is_latest" field if the given value is not nil.
func (_u *IDEReleaseUpdate) SetNillableIsLatest(v *bool) *IDEReleaseUpdate {
	if v != nil {
		_u.SetIsLatest(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *IDEReleaseUpdate) SetPublishedAt(v time.Time) *IDEReleaseUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *IDEReleaseUpdate) SetNillablePublishedAt(v *time.Time) *IDEReleaseUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// Mutation returns the IDEReleaseMutation object of the builder.
func (_u *IDEReleaseUpdate) Mutation() *IDEReleaseMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IDEReleaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IDEReleaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IDEReleaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IDEReleaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IDEReleaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := iderelease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IDEReleaseUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := iderelease.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "IDERelease.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := iderelease.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "IDERelease.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MinAppVersion(); ok {
		if err := iderelease.MinAppVersionValidator(v); err != nil {
			return &ValidationError{Name: "min_app_version", err: fmt.Errorf(`ent: validator failed for field "IDERelease.min_app_version": %w`, err)}
		}
	}
	return nil
}

func (_u *IDEReleaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(iderelease.Table, iderelease.Columns, sqlgraph.NewFieldSpec(iderelease.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(iderelease.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(iderelease.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(iderelease.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinAppVersion(); ok {
		_spec.SetField(iderelease.FieldMinAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Binaries(); ok {
		_spec.SetField(iderelease.FieldBinaries, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ReleaseNotes(); ok {
		_spec.SetField(iderelease.FieldReleaseNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsMandatory(); ok {
		_spec.SetField(iderelease.FieldIsMandatory, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsLatest(); ok {
		_spec.SetField(iderelease.FieldIsLatest, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(iderelease.FieldPublishedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{iderelease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IDEReleaseUpdateOne is the builder for updating a single IDERelease entity.
type IDEReleaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IDEReleaseMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IDEReleaseUpdateOne) SetUpdatedAt(v time.Time) *IDEReleaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *IDEReleaseUpdateOne) SetKind(v string) *IDEReleaseUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *IDEReleaseUpdateOne) SetNillableKind(v *string) *IDEReleaseUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *IDEReleaseUpdateOne) SetVersion(v string) *IDEReleaseUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *IDEReleaseUpdateOne) SetNillableVersion(v *string) *IDEReleaseUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetMinAppVersion sets the "min_app_version" field.
func (_u *IDEReleaseUpdateOne) SetMinAppVersion(v string) *IDEReleaseUpdateOne {
	_u.mutation.SetMinAppVersion(v)
	return _u
}

// SetNillableMinAppVersion sets the "min_app_version" field if the given value is not nil.
func (_u *IDEReleaseUpdateOne) SetNillableMinAppVersion(v *string) *IDEReleaseUpdateOne {
	if v != nil {
		_u.SetMinAppVersion(*v)
	}
	return _u
}

// SetBinaries sets the "binaries" field.
func (_u *IDEReleaseUpdateOne) SetBinaries(v map[string]map[string]interface{}) *IDEReleaseUpdateOne {
	_u.mutation.SetBinaries(v)
	return _u
}

// SetReleaseNotes sets the "release_notes" field.
func (_u *IDEReleaseUpdateOne) SetReleaseNotes(v string) *IDEReleaseUpdateOne {
	_u.mutation.SetReleaseNotes(v)
	return _u
}

// SetNillableReleaseNotes sets the "release_notes" field if the given value is not nil.
func (_u *IDEReleaseUpdateOne) SetNillableReleaseNotes(v *string) *IDEReleaseUpdateOne {
	if v != nil {
		_u.SetReleaseNotes(*v)
	}
	return _u
}

// SetIsMandatory sets the "is_mandatory" field.
func (_u *IDEReleaseUpdateOne) SetIsMandatory(v bool) *IDEReleaseUpdateOne {
	_u.mutation.SetIsMandatory(v)
	return _u
}

// SetNillableIsMandatory sets the "is_mandatory" field if the given value is not nil.
func (_u *IDEReleaseUpdateOne) SetNillableIsMandatory(v *bool) *IDEReleaseUpdateOne {
	if v != nil {
		_u.SetIsMandatory(*v)
	}
	return _u
}

// SetIsLatest sets the "is_latest" field.
func (_u *IDEReleaseUpdateOne) SetIsLatest(v bool) *IDEReleaseUpdateOne {
	_u.mutation.SetIsLatest(v)
	return _u
}

// SetNillableIsLatest sets the "is_latest" field if the given value is not nil.
func (_u *IDEReleaseUpdateOne) SetNillableIsLatest(v *bool) *IDEReleaseUpdateOne {
	if v != nil {
		_u.SetIsLatest(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *IDEReleaseUpdateOne) SetPublishedAt(v time.Time) *IDEReleaseUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *IDEReleaseUpdateOne) SetNillablePublishedAt(v *time.Time) *IDEReleaseUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// Mutation returns the IDEReleaseMutation object of the builder.
func (_u *IDEReleaseUpdateOne) Mutation() *IDEReleaseMutation {
	return _u.mutation
}

// Where appends a list predicates to the IDEReleaseUpdate builder.
func (_u *IDEReleaseUpdateOne) Where(ps ...predicate.IDERelease) *IDEReleaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IDEReleaseUpdateOne) Select(field string, fields ...string) *IDEReleaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IDERelease entity.
func (_u *IDEReleaseUpdateOne) Save(ctx context.Context) (*IDERelease, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IDEReleaseUpdateOne) SaveX(ctx context.Context) *IDERelease {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IDEReleaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IDEReleaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IDEReleaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := iderelease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IDEReleaseUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := iderelease.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "IDERelease.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := iderelease.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "IDERelease.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MinAppVersion(); ok {
		if err := iderelease.MinAppVersionValidator(v); err != nil {
			return &ValidationError{Name: "min_app_version", err: fmt.Errorf(`ent: validator failed for field "IDERelease.min_app_version": %w`, err)}
		}
	}
	return nil
}

func (_u *IDEReleaseUpdateOne) sqlSave(ctx context.Context) (_node *IDERelease, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(iderelease.Table, iderelease.Columns, sqlgraph.NewFieldSpec(iderelease.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IDERelease.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, iderelease.FieldID)
		for _, f := range fields {
			if !iderelease.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != iderelease.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(iderelease.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(iderelease.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(iderelease.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinAppVersion(); ok {
		_spec.SetField(iderelease.FieldMinAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Binaries(); ok {
		_spec.SetField(iderelease.FieldBinaries, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ReleaseNotes(); ok {
		_spec.SetField(iderelease.FieldReleaseNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsMandatory(); ok {
		_spec.SetField(iderelease.FieldIsMandatory, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsLatest(); ok {
		_spec.SetField(iderelease.FieldIsLatest, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(iderelease.FieldPublishedAt, field.TypeTime, value)
	}
	_node = &IDERelease{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{iderelease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
