// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/iderelease"
)

// IDERelease is the model entity for the IDERelease schema.
type IDERelease struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// MinAppVersion holds the value of the "min_app_version" field.
	MinAppVersion string `json:"min_app_version,omitempty"`
	// Binaries holds the value of the "binaries" field.
	Binaries map[string]map[string]interface{} `json:"binaries,omitempty"`
	// ReleaseNotes holds the value of the "release_notes" field.
	ReleaseNotes string `json:"release_notes,omitempty"`
	// IsMandatory holds the value of the "is_mandatory" field.
	IsMandatory bool `json:"is_mandatory,omitempty"`
	// IsLatest holds the value of the "is_latest" field.
	IsLatest bool `json:"is_latest,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt  time.Time `json:"published_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IDERelease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case iderelease.FieldBinaries:
			values[i] = new([]byte)
		case iderelease.FieldIsMandatory, iderelease.FieldIsLatest:
			values[i] = new(sql.NullBool)
		case iderelease.FieldID:
			values[i] = new(sql.NullInt64)
		case iderelease.FieldKind, iderelease.FieldVersion, iderelease.FieldMinAppVersion, iderelease.FieldReleaseNotes:
			values[i] = new(sql.NullString)
		case iderelease.FieldCreatedAt, iderelease.FieldUpdatedAt, iderelease.FieldPublishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IDERelease fields.
func (_m *IDERelease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case iderelease.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case iderelease.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case iderelease.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case iderelease.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case iderelease.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case iderelease.FieldMinAppVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field min_app_version", values[i])
			} else if value.Valid {
				_m.MinAppVersion = value.String
			}
		case iderelease.FieldBinaries:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field binaries", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Binaries); err != nil {
					return fmt.Errorf("unmarshal field binaries: %w", err)
				}
			}
		case iderelease.FieldReleaseNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_notes", values[i])
			} else if value.Valid {
				_m.ReleaseNotes = value.String
			}
		case iderelease.FieldIsMandatory:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_mandatory", values[i])
			} else if value.Valid {
				_m.IsMandatory = value.Bool
			}
		case iderelease.FieldIsLatest:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_latest", values[i])
			} else if value.Valid {
				_m.IsLatest = value.Bool
			}
		case iderelease.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IDERelease.
// This includes values selected through modifiers, order, etc.
func (_m *IDERelease) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IDERelease.
// Note that you need to call IDERelease.Unwrap() before calling this method if this IDERelease
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IDERelease) Update() *IDEReleaseUpdateOne {
	return NewIDEReleaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IDERelease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IDERelease) Unwrap() *IDERelease {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IDERelease is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IDERelease) String() string {
	var builder strings.Builder
	builder.WriteString("IDERelease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("min_app_version=")
	builder.WriteString(_m.MinAppVersion)
	builder.WriteString(", ")
	builder.WriteString("binaries=")
	builder.WriteString(fmt.Sprintf("%v", _m.Binaries))
	builder.WriteString(", ")
	builder.WriteString("release_notes=")
	builder.WriteString(_m.ReleaseNotes)
	builder.WriteString(", ")
	builder.WriteString("is_mandatory=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsMandatory))
	builder.WriteString(", ")
	builder.WriteString("is_latest=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsLatest))
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(_m.PublishedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IDEReleases is a parsable slice of IDERelease.
type IDEReleases []*IDERelease
