// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/iderelease"
)

// IDEReleaseCreate is the builder for creating a IDERelease entity.
type IDEReleaseCreate struct {
	config
	mutation *IDEReleaseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IDEReleaseCreate) SetCreatedAt(v time.Time) *IDEReleaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IDEReleaseCreate) SetNillableCreatedAt(v *time.Time) *IDEReleaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IDEReleaseCreate) SetUpdatedAt(v time.Time) *IDEReleaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IDEReleaseCreate) SetNillableUpdatedAt(v *time.Time) *IDEReleaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *IDEReleaseCreate) SetKind(v string) *IDEReleaseCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *IDEReleaseCreate) SetVersion(v string) *IDEReleaseCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetMinAppVersion sets the "min_app_version" field.
func (_c *IDEReleaseCreate) SetMinAppVersion(v string) *IDEReleaseCreate {
	_c.mutation.SetMinAppVersion(v)
	return _c
}

// SetNillableMinAppVersion sets the "min_app_version" field if the given value is not nil.
func (_c *IDEReleaseCreate) SetNillableMinAppVersion(v *string) *IDEReleaseCreate {
	if v != nil {
		_c.SetMinAppVersion(*v)
	}
	return _c
}

// SetBinaries sets the "binaries" field.
func (_c *IDEReleaseCreate) SetBinaries(v map[string]map[string]interface{}) *IDEReleaseCreate {
	_c.mutation.SetBinaries(v)
	return _c
}

// SetReleaseNotes sets the "release_notes" field.
func (_c *IDEReleaseCreate) SetReleaseNotes(v string) *IDEReleaseCreate {
	_c.mutation.SetReleaseNotes(v)
	return _c
}

// SetNillableReleaseNotes sets the "release_notes" field if the given value is not nil.
func (_c *IDEReleaseCreate) SetNillableReleaseNotes(v *string) *IDEReleaseCreate {
	if v != nil {
		_c.SetReleaseNotes(*v)
	}
	return _c
}

// SetIsMandatory sets the "is_mandatory" field.
func (_c *IDEReleaseCreate) SetIsMandatory(v bool) *IDEReleaseCreate {
	_c.mutation.SetIsMandatory(v)
	return _c
}

// SetNillableIsMandatory sets the "is_mandatory" field if the given value is not nil.
func (_c *IDEReleaseCreate) SetNillableIsMandatory(v *bool) *IDEReleaseCreate {
	if v != nil {
		_c.SetIsMandatory(*v)
	}
	return _c
}

// SetIsLatest sets the "is_latest" field.
func (_c *IDEReleaseCreate) SetIsLatest(v bool) *IDEReleaseCreate {
	_c.mutation.SetIsLatest(v)
	return _c
}

// SetNillableIsLatest sets the "is_latest" field if the given value is not nil.
func (_c *IDEReleaseCreate) SetNillableIsLatest(v *bool) *IDEReleaseCreate {
	if v != nil {
		_c.SetIsLatest(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *IDEReleaseCreate) SetPublishedAt(v time.Time) *IDEReleaseCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// Mutation returns the IDEReleaseMutation object of the builder.
func (_c *IDEReleaseCreate) Mutation() *IDEReleaseMutation {
	return _c.mutation
}

// Save creates the IDERelease in the database.
func (_c *IDEReleaseCreate) Save(ctx context.Context) (*IDERelease, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IDEReleaseCreate) SaveX(ctx context.Context) *IDERelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IDEReleaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IDEReleaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IDEReleaseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := iderelease.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := iderelease.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.MinAppVersion(); !ok {
		v := iderelease.DefaultMinAppVersion
		_c.mutation.SetMinAppVersion(v)
	}
	if _, ok := _c.mutation.Binaries(); !ok {
		v := iderelease.DefaultBinaries()
		_c.mutation.SetBinaries(v)
	}
	if _, ok := _c.mutation.ReleaseNotes(); !ok {
		v := iderelease.DefaultReleaseNotes
		_c.mutation.SetReleaseNotes(v)
	}
	if _, ok := _c.mutation.IsMandatory(); !ok {
		v := iderelease.DefaultIsMandatory
		_c.mutation.SetIsMandatory(v)
	}
	if _, ok := _c.mutation.IsLatest(); !ok {
		v := iderelease.DefaultIsLatest
		_c.mutation.SetIsLatest(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IDEReleaseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IDERelease.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IDERelease.updated_at"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "IDERelease.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := iderelease.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "IDERelease.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "IDERelease.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := iderelease.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "IDERelease.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MinAppVersion(); !ok {
		return &ValidationError{Name: "min_app_version", err: errors.New(`ent: missing required field "IDERelease.min_app_version"`)}
	}
	if v, ok := _c.mutation.MinAppVersion(); ok {
		if err := iderelease.MinAppVersionValidator(v); err != nil {
			return &ValidationError{Name: "min_app_version", err: fmt.Errorf(`ent: validator failed for field "IDERelease.min_app_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Binaries(); !ok {
		return &ValidationError{Name: "binaries", err: errors.New(`ent: missing required field "IDERelease.binaries"`)}
	}
	if _, ok := _c.mutation.ReleaseNotes(); !ok {
		return &ValidationError{Name: "release_notes", err: errors.New(`ent: missing required field "IDERelease.release_notes"`)}
	}
	if _, ok := _c.mutation.IsMandatory(); !ok {
		return &ValidationError{Name: "is_mandatory", err: errors.New(`ent: missing required field "IDERelease.is_mandatory"`)}
	}
	if _, ok := _c.mutation.IsLatest(); !ok {
		return &ValidationError{Name: "is_latest", err: errors.New(`ent: missing required field "IDERelease.is_latest"`)}
	}
	if _, ok := _c.mutation.PublishedAt(); !ok {
		return &ValidationError{Name: "published_at", err: errors.New(`ent: missing required field "IDERelease.published_at"`)}
	}
	return nil
}

func (_c *IDEReleaseCreate) sqlSave(ctx context.Context) (*IDERelease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IDEReleaseCreate) createSpec() (*IDERelease, *sqlgraph.CreateSpec) {
	var (
		_node = &IDERelease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(iderelease.Table, sqlgraph.NewFieldSpec(iderelease.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(iderelease.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(iderelease.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(iderelease.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(iderelease.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.MinAppVersion(); ok {
		_spec.SetField(iderelease.FieldMinAppVersion, field.TypeString, value)
		_node.MinAppVersion = value
	}
	if value, ok := _c.mutation.Binaries(); ok {
		_spec.SetField(iderelease.FieldBinaries, field.TypeJSON, value)
		_node.Binaries = value
	}
	if value, ok := _c.mutation.ReleaseNotes(); ok {
		_spec.SetField(iderelease.FieldReleaseNotes, field.TypeString, value)
		_node.ReleaseNotes = value
	}
	if value, ok := _c.mutation.IsMandatory(); ok {
		_spec.SetField(iderelease.FieldIsMandatory, field.TypeBool, value)
		_node.IsMandatory = value
	}
	if value, ok := _c.mutation.IsLatest(); ok {
		_spec.SetField(iderelease.FieldIsLatest, field.TypeBool, value)
		_node.IsLatest = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(iderelease.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IDERelease.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IDEReleaseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IDEReleaseCreate) OnConflict(opts ...sql.ConflictOption) *IDEReleaseUpsertOne {
	_c.conflict = opts
	return &IDEReleaseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IDERelease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IDEReleaseCreate) OnConflictColumns(columns ...string) *IDEReleaseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IDEReleaseUpsertOne{
		create: _c,
	}
}

type (
	// IDEReleaseUpsertOne is the builder for "upsert"-ing
	//  one IDERelease node.
	IDEReleaseUpsertOne struct {
		create *IDEReleaseCreate
	}

	// IDEReleaseUpsert is the "OnConflict" setter.
	IDEReleaseUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IDEReleaseUpsert) SetUpdatedAt(v time.Time) *IDEReleaseUpsert {
	u.Set(iderelease.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IDEReleaseUpsert) UpdateUpdatedAt() *IDEReleaseUpsert {
	u.SetExcluded(iderelease.FieldUpdatedAt)
	return u
}

// SetKind sets the "kind" field.
func (u *IDEReleaseUpsert) SetKind(v string) *IDEReleaseUpsert {
	u.Set(iderelease.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *IDEReleaseUpsert) UpdateKind() *IDEReleaseUpsert {
	u.SetExcluded(iderelease.FieldKind)
	return u
}

// SetVersion sets the "version" field.
func (u *IDEReleaseUpsert) SetVersion(v string) *IDEReleaseUpsert {
	u.Set(iderelease.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *IDEReleaseUpsert) UpdateVersion() *IDEReleaseUpsert {
	u.SetExcluded(iderelease.FieldVersion)
	return u
}

// SetMinAppVersion sets the "min_app_version" field.
func (u *IDEReleaseUpsert) SetMinAppVersion(v string) *IDEReleaseUpsert {
	u.Set(iderelease.FieldMinAppVersion, v)
	return u
}

// UpdateMinAppVersion sets the "min_app_version" field to the value that was provided on create.
func (u *IDEReleaseUpsert) UpdateMinAppVersion() *IDEReleaseUpsert {
	u.SetExcluded(iderelease.FieldMinAppVersion)
	return u
}

// SetBinaries sets the "binaries" field.
func (u *IDEReleaseUpsert) SetBinaries(v map[string]map[string]interface{}) *IDEReleaseUpsert {
	u.Set(iderelease.FieldBinaries, v)
	return u
}

// UpdateBinaries sets the "binaries" field to the value that was provided on create.
func (u *IDEReleaseUpsert) UpdateBinaries() *IDEReleaseUpsert {
	u.SetExcluded(iderelease.FieldBinaries)
	return u
}

// SetReleaseNotes sets the "release_notes" field.
func (u *IDEReleaseUpsert) SetReleaseNotes(v string) *IDEReleaseUpsert {
	u.Set(iderelease.FieldReleaseNotes, v)
	return u
}

// UpdateReleaseNotes sets the "release_notes" field to the value that was provided on create.
func (u *IDEReleaseUpsert) UpdateReleaseNotes() *IDEReleaseUpsert {
	u.SetExcluded(iderelease.FieldReleaseNotes)
	return u
}

// SetIsMandatory sets the "is_mandatory" field.
func (u *IDEReleaseUpsert) SetIsMandatory(v bool) *IDEReleaseUpsert {
	u.Set(iderelease.FieldIsMandatory, v)
	return u
}

// UpdateIsMandatory sets the "is_mandatory" field to the value that was provided on create.
func (u *IDEReleaseUpsert) UpdateIsMandatory() *IDEReleaseUpsert {
	u.SetExcluded(iderelease.FieldIsMandatory)
	return u
}

// SetIsLatest sets the "is_latest" field.
func (u *IDEReleaseUpsert) SetIsLatest(v bool) *IDEReleaseUpsert {
	u.Set(iderelease.FieldIsLatest, v)
	return u
}

// UpdateIsLatest sets the "is_latest" field to the value that was provided on create.
func (u *IDEReleaseUpsert) UpdateIsLatest() *IDEReleaseUpsert {
	u.SetExcluded(iderelease.FieldIsLatest)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *IDEReleaseUpsert) SetPublishedAt(v time.Time) *IDEReleaseUpsert {
	u.Set(iderelease.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *IDEReleaseUpsert) UpdatePublishedAt() *IDEReleaseUpsert {
	u.SetExcluded(iderelease.FieldPublishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IDERelease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IDEReleaseUpsertOne) UpdateNewValues() *IDEReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(iderelease.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IDERelease.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IDEReleaseUpsertOne) Ignore() *IDEReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IDEReleaseUpsertOne) DoNothing() *IDEReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IDEReleaseCreate.OnConflict
// documentation for more info.
func (u *IDEReleaseUpsertOne) Update(set func(*IDEReleaseUpsert)) *IDEReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IDEReleaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IDEReleaseUpsertOne) SetUpdatedAt(v time.Time) *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IDEReleaseUpsertOne) UpdateUpdatedAt() *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *IDEReleaseUpsertOne) SetKind(v string) *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *IDEReleaseUpsertOne) UpdateKind() *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateKind()
	})
}

// SetVersion sets the "version" field.
func (u *IDEReleaseUpsertOne) SetVersion(v string) *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *IDEReleaseUpsertOne) UpdateVersion() *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateVersion()
	})
}

// SetMinAppVersion sets the "min_app_version" field.
func (u *IDEReleaseUpsertOne) SetMinAppVersion(v string) *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetMinAppVersion(v)
	})
}

// UpdateMinAppVersion sets the "min_app_version" field to the value that was provided on create.
func (u *IDEReleaseUpsertOne) UpdateMinAppVersion() *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateMinAppVersion()
	})
}

// SetBinaries sets the "binaries" field.
func (u *IDEReleaseUpsertOne) SetBinaries(v map[string]map[string]interface{}) *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetBinaries(v)
	})
}

// UpdateBinaries sets the "binaries" field to the value that was provided on create.
func (u *IDEReleaseUpsertOne) UpdateBinaries() *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateBinaries()
	})
}

// SetReleaseNotes sets the "release_notes" field.
func (u *IDEReleaseUpsertOne) SetReleaseNotes(v string) *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetReleaseNotes(v)
	})
}

// UpdateReleaseNotes sets the "release_notes" field to the value that was provided on create.
func (u *IDEReleaseUpsertOne) UpdateReleaseNotes() *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateReleaseNotes()
	})
}

// SetIsMandatory sets the "is_mandatory" field.
func (u *IDEReleaseUpsertOne) SetIsMandatory(v bool) *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetIsMandatory(v)
	})
}

// UpdateIsMandatory sets the "is_mandatory" field to the value that was provided on create.
func (u *IDEReleaseUpsertOne) UpdateIsMandatory() *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateIsMandatory()
	})
}

// SetIsLatest sets the "is_latest" field.
func (u *IDEReleaseUpsertOne) SetIsLatest(v bool) *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetIsLatest(v)
	})
}

// UpdateIsLatest sets the "is_latest" field to the value that was provided on create.
func (u *IDEReleaseUpsertOne) UpdateIsLatest() *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateIsLatest()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *IDEReleaseUpsertOne) SetPublishedAt(v time.Time) *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *IDEReleaseUpsertOne) UpdatePublishedAt() *IDEReleaseUpsertOne {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdatePublishedAt()
	})
}

// Exec executes the query.
func (u *IDEReleaseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IDEReleaseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IDEReleaseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IDEReleaseUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IDEReleaseUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IDEReleaseCreateBulk is the builder for creating many IDERelease entities in bulk.
type IDEReleaseCreateBulk struct {
	config
	err      error
	builders []*IDEReleaseCreate
	conflict []sql.ConflictOption
}

// Save creates the IDERelease entities in the database.
func (_c *IDEReleaseCreateBulk) Save(ctx context.Context) ([]*IDERelease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IDERelease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IDEReleaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IDEReleaseCreateBulk) SaveX(ctx context.Context) []*IDERelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IDEReleaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IDEReleaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IDERelease.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IDEReleaseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IDEReleaseCreateBulk) OnConflict(opts ...sql.ConflictOption) *IDEReleaseUpsertBulk {
	_c.conflict = opts
	return &IDEReleaseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IDERelease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IDEReleaseCreateBulk) OnConflictColumns(columns ...string) *IDEReleaseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IDEReleaseUpsertBulk{
		create: _c,
	}
}

// IDEReleaseUpsertBulk is the builder for "upsert"-ing
// a bulk of IDERelease nodes.
type IDEReleaseUpsertBulk struct {
	create *IDEReleaseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IDERelease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IDEReleaseUpsertBulk) UpdateNewValues() *IDEReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(iderelease.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IDERelease.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IDEReleaseUpsertBulk) Ignore() *IDEReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IDEReleaseUpsertBulk) DoNothing() *IDEReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IDEReleaseCreateBulk.OnConflict
// documentation for more info.
func (u *IDEReleaseUpsertBulk) Update(set func(*IDEReleaseUpsert)) *IDEReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IDEReleaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IDEReleaseUpsertBulk) SetUpdatedAt(v time.Time) *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IDEReleaseUpsertBulk) UpdateUpdatedAt() *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *IDEReleaseUpsertBulk) SetKind(v string) *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *IDEReleaseUpsertBulk) UpdateKind() *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateKind()
	})
}

// SetVersion sets the "version" field.
func (u *IDEReleaseUpsertBulk) SetVersion(v string) *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *IDEReleaseUpsertBulk) UpdateVersion() *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateVersion()
	})
}

// SetMinAppVersion sets the "min_app_version" field.
func (u *IDEReleaseUpsertBulk) SetMinAppVersion(v string) *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetMinAppVersion(v)
	})
}

// UpdateMinAppVersion sets the "min_app_version" field to the value that was provided on create.
func (u *IDEReleaseUpsertBulk) UpdateMinAppVersion() *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateMinAppVersion()
	})
}

// SetBinaries sets the "binaries" field.
func (u *IDEReleaseUpsertBulk) SetBinaries(v map[string]map[string]interface{}) *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetBinaries(v)
	})
}

// UpdateBinaries sets the "binaries" field to the value that was provided on create.
func (u *IDEReleaseUpsertBulk) UpdateBinaries() *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateBinaries()
	})
}

// SetReleaseNotes sets the "release_notes" field.
func (u *IDEReleaseUpsertBulk) SetReleaseNotes(v string) *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetReleaseNotes(v)
	})
}

// UpdateReleaseNotes sets the "release_notes" field to the value that was provided on create.
func (u *IDEReleaseUpsertBulk) UpdateReleaseNotes() *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateReleaseNotes()
	})
}

// SetIsMandatory sets the "is_mandatory" field.
func (u *IDEReleaseUpsertBulk) SetIsMandatory(v bool) *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetIsMandatory(v)
	})
}

// UpdateIsMandatory sets the "is_mandatory" field to the value that was provided on create.
func (u *IDEReleaseUpsertBulk) UpdateIsMandatory() *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateIsMandatory()
	})
}

// SetIsLatest sets the "is_latest" field.
func (u *IDEReleaseUpsertBulk) SetIsLatest(v bool) *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetIsLatest(v)
	})
}

// UpdateIsLatest sets the "is_latest" field to the value that was provided on create.
func (u *IDEReleaseUpsertBulk) UpdateIsLatest() *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdateIsLatest()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *IDEReleaseUpsertBulk) SetPublishedAt(v time.Time) *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *IDEReleaseUpsertBulk) UpdatePublishedAt() *IDEReleaseUpsertBulk {
	return u.Update(func(s *IDEReleaseUpsert) {
		s.UpdatePublishedAt()
	})
}

// Exec executes the query.
func (u *IDEReleaseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IDEReleaseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IDEReleaseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IDEReleaseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
