// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/idesession"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// IDESessionCreate is the builder for creating a IDESession entity.
type IDESessionCreate struct {
	config
	mutation *IDESessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IDESessionCreate) SetCreatedAt(v time.Time) *IDESessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IDESessionCreate) SetNillableCreatedAt(v *time.Time) *IDESessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IDESessionCreate) SetUpdatedAt(v time.Time) *IDESessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IDESessionCreate) SetNillableUpdatedAt(v *time.Time) *IDESessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *IDESessionCreate) SetSessionID(v string) *IDESessionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *IDESessionCreate) SetUserID(v int64) *IDESessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetJwtTokenHash sets the "jwt_token_hash" field.
func (_c *IDESessionCreate) SetJwtTokenHash(v string) *IDESessionCreate {
	_c.mutation.SetJwtTokenHash(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *IDESessionCreate) SetClientID(v string) *IDESessionCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_c *IDESessionCreate) SetNillableClientID(v *string) *IDESessionCreate {
	if v != nil {
		_c.SetClientID(*v)
	}
	return _c
}

// SetClientVersion sets the "client_version" field.
func (_c *IDESessionCreate) SetClientVersion(v string) *IDESessionCreate {
	_c.mutation.SetClientVersion(v)
	return _c
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (_c *IDESessionCreate) SetNillableClientVersion(v *string) *IDESessionCreate {
	if v != nil {
		_c.SetClientVersion(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *IDESessionCreate) SetPlatform(v string) *IDESessionCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *IDESessionCreate) SetNillablePlatform(v *string) *IDESessionCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *IDESessionCreate) SetDeviceID(v string) *IDESessionCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_c *IDESessionCreate) SetNillableDeviceID(v *string) *IDESessionCreate {
	if v != nil {
		_c.SetDeviceID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *IDESessionCreate) SetExpiresAt(v time.Time) *IDESessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *IDESessionCreate) SetLastUsedAt(v time.Time) *IDESessionCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetRevoked sets the "revoked" field.
func (_c *IDESessionCreate) SetRevoked(v bool) *IDESessionCreate {
	_c.mutation.SetRevoked(v)
	return _c
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_c *IDESessionCreate) SetNillableRevoked(v *bool) *IDESessionCreate {
	if v != nil {
		_c.SetRevoked(*v)
	}
	return _c
}

// SetRevokeReason sets the "revoke_reason" field.
func (_c *IDESessionCreate) SetRevokeReason(v string) *IDESessionCreate {
	_c.mutation.SetRevokeReason(v)
	return _c
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_c *IDESessionCreate) SetNillableRevokeReason(v *string) *IDESessionCreate {
	if v != nil {
		_c.SetRevokeReason(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *IDESessionCreate) SetUser(v *User) *IDESessionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the IDESessionMutation object of the builder.
func (_c *IDESessionCreate) Mutation() *IDESessionMutation {
	return _c.mutation
}

// Save creates the IDESession in the database.
func (_c *IDESessionCreate) Save(ctx context.Context) (*IDESession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IDESessionCreate) SaveX(ctx context.Context) *IDESession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IDESessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IDESessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IDESessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := idesession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := idesession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		v := idesession.DefaultClientID
		_c.mutation.SetClientID(v)
	}
	if _, ok := _c.mutation.ClientVersion(); !ok {
		v := idesession.DefaultClientVersion
		_c.mutation.SetClientVersion(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := idesession.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		v := idesession.DefaultDeviceID
		_c.mutation.SetDeviceID(v)
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		v := idesession.DefaultRevoked
		_c.mutation.SetRevoked(v)
	}
	if _, ok := _c.mutation.RevokeReason(); !ok {
		v := idesession.DefaultRevokeReason
		_c.mutation.SetRevokeReason(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IDESessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IDESession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IDESession.updated_at"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "IDESession.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := idesession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "IDESession.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "IDESession.user_id"`)}
	}
	if _, ok := _c.mutation.JwtTokenHash(); !ok {
		return &ValidationError{Name: "jwt_token_hash", err: errors.New(`ent: missing required field "IDESession.jwt_token_hash"`)}
	}
	if v, ok := _c.mutation.JwtTokenHash(); ok {
		if err := idesession.JwtTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "jwt_token_hash", err: fmt.Errorf(`ent: validator failed for field "IDESession.jwt_token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "IDESession.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := idesession.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "IDESession.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientVersion(); !ok {
		return &ValidationError{Name: "client_version", err: errors.New(`ent: missing required field "IDESession.client_version"`)}
	}
	if v, ok := _c.mutation.ClientVersion(); ok {
		if err := idesession.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "IDESession.client_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "IDESession.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := idesession.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "IDESession.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "IDESession.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := idesession.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "IDESession.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "IDESession.expires_at"`)}
	}
	if _, ok := _c.mutation.LastUsedAt(); !ok {
		return &ValidationError{Name: "last_used_at", err: errors.New(`ent: missing required field "IDESession.last_used_at"`)}
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		return &ValidationError{Name: "revoked", err: errors.New(`ent: missing required field "IDESession.revoked"`)}
	}
	if _, ok := _c.mutation.RevokeReason(); !ok {
		return &ValidationError{Name: "revoke_reason", err: errors.New(`ent: missing required field "IDESession.revoke_reason"`)}
	}
	if v, ok := _c.mutation.RevokeReason(); ok {
		if err := idesession.RevokeReasonValidator(v); err != nil {
			return &ValidationError{Name: "revoke_reason", err: fmt.Errorf(`ent: validator failed for field "IDESession.revoke_reason": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "IDESession.user"`)}
	}
	return nil
}

func (_c *IDESessionCreate) sqlSave(ctx context.Context) (*IDESession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IDESessionCreate) createSpec() (*IDESession, *sqlgraph.CreateSpec) {
	var (
		_node = &IDESession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(idesession.Table, sqlgraph.NewFieldSpec(idesession.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(idesession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(idesession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(idesession.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.JwtTokenHash(); ok {
		_spec.SetField(idesession.FieldJwtTokenHash, field.TypeString, value)
		_node.JwtTokenHash = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(idesession.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientVersion(); ok {
		_spec.SetField(idesession.FieldClientVersion, field.TypeString, value)
		_node.ClientVersion = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(idesession.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(idesession.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(idesession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(idesession.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = value
	}
	if value, ok := _c.mutation.Revoked(); ok {
		_spec.SetField(idesession.FieldRevoked, field.TypeBool, value)
		_node.Revoked = value
	}
	if value, ok := _c.mutation.RevokeReason(); ok {
		_spec.SetField(idesession.FieldRevokeReason, field.TypeString, value)
		_node.RevokeReason = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idesession.UserTable,
			Columns: []string{idesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IDESession.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IDESessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IDESessionCreate) OnConflict(opts ...sql.ConflictOption) *IDESessionUpsertOne {
	_c.conflict = opts
	return &IDESessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IDESession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IDESessionCreate) OnConflictColumns(columns ...string) *IDESessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IDESessionUpsertOne{
		create: _c,
	}
}

type (
	// IDESessionUpsertOne is the builder for "upsert"-ing
	//  one IDESession node.
	IDESessionUpsertOne struct {
		create *IDESessionCreate
	}

	// IDESessionUpsert is the "OnConflict" setter.
	IDESessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IDESessionUpsert) SetUpdatedAt(v time.Time) *IDESessionUpsert {
	u.Set(idesession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateUpdatedAt() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *IDESessionUpsert) SetUserID(v int64) *IDESessionUpsert {
	u.Set(idesession.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateUserID() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldUserID)
	return u
}

// SetJwtTokenHash sets the "jwt_token_hash" field.
func (u *IDESessionUpsert) SetJwtTokenHash(v string) *IDESessionUpsert {
	u.Set(idesession.FieldJwtTokenHash, v)
	return u
}

// UpdateJwtTokenHash sets the "jwt_token_hash" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateJwtTokenHash() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldJwtTokenHash)
	return u
}

// SetClientID sets the "client_id" field.
func (u *IDESessionUpsert) SetClientID(v string) *IDESessionUpsert {
	u.Set(idesession.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateClientID() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldClientID)
	return u
}

// SetClientVersion sets the "client_version" field.
func (u *IDESessionUpsert) SetClientVersion(v string) *IDESessionUpsert {
	u.Set(idesession.FieldClientVersion, v)
	return u
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateClientVersion() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldClientVersion)
	return u
}

// SetPlatform sets the "platform" field.
func (u *IDESessionUpsert) SetPlatform(v string) *IDESessionUpsert {
	u.Set(idesession.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdatePlatform() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldPlatform)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *IDESessionUpsert) SetDeviceID(v string) *IDESessionUpsert {
	u.Set(idesession.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateDeviceID() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldDeviceID)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *IDESessionUpsert) SetExpiresAt(v time.Time) *IDESessionUpsert {
	u.Set(idesession.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateExpiresAt() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldExpiresAt)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *IDESessionUpsert) SetLastUsedAt(v time.Time) *IDESessionUpsert {
	u.Set(idesession.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateLastUsedAt() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldLastUsedAt)
	return u
}

// SetRevoked sets the "revoked" field.
func (u *IDESessionUpsert) SetRevoked(v bool) *IDESessionUpsert {
	u.Set(idesession.FieldRevoked, v)
	return u
}

// UpdateRevoked sets the "revoked" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateRevoked() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldRevoked)
	return u
}

// SetRevokeReason sets the "revoke_reason" field.
func (u *IDESessionUpsert) SetRevokeReason(v string) *IDESessionUpsert {
	u.Set(idesession.FieldRevokeReason, v)
	return u
}

// UpdateRevokeReason sets the "revoke_reason" field to the value that was provided on create.
func (u *IDESessionUpsert) UpdateRevokeReason() *IDESessionUpsert {
	u.SetExcluded(idesession.FieldRevokeReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IDESession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IDESessionUpsertOne) UpdateNewValues() *IDESessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(idesession.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.SessionID(); exists {
			s.SetIgnore(idesession.FieldSessionID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IDESession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IDESessionUpsertOne) Ignore() *IDESessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IDESessionUpsertOne) DoNothing() *IDESessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IDESessionCreate.OnConflict
// documentation for more info.
func (u *IDESessionUpsertOne) Update(set func(*IDESessionUpsert)) *IDESessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IDESessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IDESessionUpsertOne) SetUpdatedAt(v time.Time) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateUpdatedAt() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *IDESessionUpsertOne) SetUserID(v int64) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateUserID() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateUserID()
	})
}

// SetJwtTokenHash sets the "jwt_token_hash" field.
func (u *IDESessionUpsertOne) SetJwtTokenHash(v string) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetJwtTokenHash(v)
	})
}

// UpdateJwtTokenHash sets the "jwt_token_hash" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateJwtTokenHash() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateJwtTokenHash()
	})
}

// SetClientID sets the "client_id" field.
func (u *IDESessionUpsertOne) SetClientID(v string) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateClientID() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateClientID()
	})
}

// SetClientVersion sets the "client_version" field.
func (u *IDESessionUpsertOne) SetClientVersion(v string) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetClientVersion(v)
	})
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateClientVersion() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateClientVersion()
	})
}

// SetPlatform sets the "platform" field.
func (u *IDESessionUpsertOne) SetPlatform(v string) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdatePlatform() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdatePlatform()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *IDESessionUpsertOne) SetDeviceID(v string) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateDeviceID() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateDeviceID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *IDESessionUpsertOne) SetExpiresAt(v time.Time) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateExpiresAt() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *IDESessionUpsertOne) SetLastUsedAt(v time.Time) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateLastUsedAt() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateLastUsedAt()
	})
}

// SetRevoked sets the "revoked" field.
func (u *IDESessionUpsertOne) SetRevoked(v bool) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetRevoked(v)
	})
}

// UpdateRevoked sets the "revoked" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateRevoked() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateRevoked()
	})
}

// SetRevokeReason sets the "revoke_reason" field.
func (u *IDESessionUpsertOne) SetRevokeReason(v string) *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetRevokeReason(v)
	})
}

// UpdateRevokeReason sets the "revoke_reason" field to the value that was provided on create.
func (u *IDESessionUpsertOne) UpdateRevokeReason() *IDESessionUpsertOne {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateRevokeReason()
	})
}

// Exec executes the query.
func (u *IDESessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IDESessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IDESessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IDESessionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IDESessionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IDESessionCreateBulk is the builder for creating many IDESession entities in bulk.
type IDESessionCreateBulk struct {
	config
	err      error
	builders []*IDESessionCreate
	conflict []sql.ConflictOption
}

// Save creates the IDESession entities in the database.
func (_c *IDESessionCreateBulk) Save(ctx context.Context) ([]*IDESession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IDESession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IDESessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IDESessionCreateBulk) SaveX(ctx context.Context) []*IDESession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IDESessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IDESessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IDESession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IDESessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IDESessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *IDESessionUpsertBulk {
	_c.conflict = opts
	return &IDESessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IDESession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IDESessionCreateBulk) OnConflictColumns(columns ...string) *IDESessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IDESessionUpsertBulk{
		create: _c,
	}
}

// IDESessionUpsertBulk is the builder for "upsert"-ing
// a bulk of IDESession nodes.
type IDESessionUpsertBulk struct {
	create *IDESessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IDESession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IDESessionUpsertBulk) UpdateNewValues() *IDESessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(idesession.FieldCreatedAt)
			}
			if _, exists := b.mutation.SessionID(); exists {
				s.SetIgnore(idesession.FieldSessionID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IDESession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IDESessionUpsertBulk) Ignore() *IDESessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IDESessionUpsertBulk) DoNothing() *IDESessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IDESessionCreateBulk.OnConflict
// documentation for more info.
func (u *IDESessionUpsertBulk) Update(set func(*IDESessionUpsert)) *IDESessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IDESessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IDESessionUpsertBulk) SetUpdatedAt(v time.Time) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateUpdatedAt() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *IDESessionUpsertBulk) SetUserID(v int64) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateUserID() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateUserID()
	})
}

// SetJwtTokenHash sets the "jwt_token_hash" field.
func (u *IDESessionUpsertBulk) SetJwtTokenHash(v string) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetJwtTokenHash(v)
	})
}

// UpdateJwtTokenHash sets the "jwt_token_hash" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateJwtTokenHash() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateJwtTokenHash()
	})
}

// SetClientID sets the "client_id" field.
func (u *IDESessionUpsertBulk) SetClientID(v string) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateClientID() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateClientID()
	})
}

// SetClientVersion sets the "client_version" field.
func (u *IDESessionUpsertBulk) SetClientVersion(v string) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetClientVersion(v)
	})
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateClientVersion() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateClientVersion()
	})
}

// SetPlatform sets the "platform" field.
func (u *IDESessionUpsertBulk) SetPlatform(v string) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdatePlatform() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdatePlatform()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *IDESessionUpsertBulk) SetDeviceID(v string) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateDeviceID() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateDeviceID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *IDESessionUpsertBulk) SetExpiresAt(v time.Time) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateExpiresAt() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *IDESessionUpsertBulk) SetLastUsedAt(v time.Time) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateLastUsedAt() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateLastUsedAt()
	})
}

// SetRevoked sets the "revoked" field.
func (u *IDESessionUpsertBulk) SetRevoked(v bool) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetRevoked(v)
	})
}

// UpdateRevoked sets the "revoked" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateRevoked() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateRevoked()
	})
}

// SetRevokeReason sets the "revoke_reason" field.
func (u *IDESessionUpsertBulk) SetRevokeReason(v string) *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.SetRevokeReason(v)
	})
}

// UpdateRevokeReason sets the "revoke_reason" field to the value that was provided on create.
func (u *IDESessionUpsertBulk) UpdateRevokeReason() *IDESessionUpsertBulk {
	return u.Update(func(s *IDESessionUpsert) {
		s.UpdateRevokeReason()
	})
}

// Exec executes the query.
func (u *IDESessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IDESessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IDESessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IDESessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
