// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/idesession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// IDESessionUpdate is the builder for updating IDESession entities.
type IDESessionUpdate struct {
	config
	hooks    []Hook
	mutation *IDESessionMutation
}

// Where appends a list predicates to the IDESessionUpdate builder.
func (_u *IDESessionUpdate) Where(ps ...predicate.IDESession) *IDESessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IDESessionUpdate) SetUpdatedAt(v time.Time) *IDESessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *IDESessionUpdate) SetUserID(v int64) *IDESessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillableUserID(v *int64) *IDESessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetJwtTokenHash sets the "jwt_token_hash" field.
func (_u *IDESessionUpdate) SetJwtTokenHash(v string) *IDESessionUpdate {
	_u.mutation.SetJwtTokenHash(v)
	return _u
}

// SetNillableJwtTokenHash sets the "jwt_token_hash" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillableJwtTokenHash(v *string) *IDESessionUpdate {
	if v != nil {
		_u.SetJwtTokenHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *IDESessionUpdate) SetClientID(v string) *IDESessionUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillableClientID(v *string) *IDESessionUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientVersion sets the "client_version" field.
func (_u *IDESessionUpdate) SetClientVersion(v string) *IDESessionUpdate {
	_u.mutation.SetClientVersion(v)
	return _u
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillableClientVersion(v *string) *IDESessionUpdate {
	if v != nil {
		_u.SetClientVersion(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *IDESessionUpdate) SetPlatform(v string) *IDESessionUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillablePlatform(v *string) *IDESessionUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *IDESessionUpdate) SetDeviceID(v string) *IDESessionUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillableDeviceID(v *string) *IDESessionUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IDESessionUpdate) SetExpiresAt(v time.Time) *IDESessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillableExpiresAt(v *time.Time) *IDESessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *IDESessionUpdate) SetLastUsedAt(v time.Time) *IDESessionUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillableLastUsedAt(v *time.Time) *IDESessionUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *IDESessionUpdate) SetRevoked(v bool) *IDESessionUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillableRevoked(v *bool) *IDESessionUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *IDESessionUpdate) SetRevokeReason(v string) *IDESessionUpdate {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *IDESessionUpdate) SetNillableRevokeReason(v *string) *IDESessionUpdate {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *IDESessionUpdate) SetUser(v *User) *IDESessionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the IDESessionMutation object of the builder.
func (_u *IDESessionUpdate) Mutation() *IDESessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *IDESessionUpdate) ClearUser() *IDESessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IDESessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IDESessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IDESessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IDESessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IDESessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := idesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IDESessionUpdate) check() error {
	if v, ok := _u.mutation.JwtTokenHash(); ok {
		if err := idesession.JwtTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "jwt_token_hash", err: fmt.Errorf(`ent: validator failed for field "IDESession.jwt_token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := idesession.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "IDESession.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientVersion(); ok {
		if err := idesession.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "IDESession.client_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := idesession.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "IDESession.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := idesession.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "IDESession.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevokeReason(); ok {
		if err := idesession.RevokeReasonValidator(v); err != nil {
			return &ValidationError{Name: "revoke_reason", err: fmt.Errorf(`ent: validator failed for field "IDESession.revoke_reason": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IDESession.user"`)
	}
	return nil
}

func (_u *IDESessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(idesession.Table, idesession.Columns, sqlgraph.NewFieldSpec(idesession.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(idesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.JwtTokenHash(); ok {
		_spec.SetField(idesession.FieldJwtTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(idesession.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientVersion(); ok {
		_spec.SetField(idesession.FieldClientVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(idesession.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(idesession.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(idesession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(idesession.FieldLastUsedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(idesession.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(idesession.FieldRevokeReason, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idesession.UserTable,
			Columns: []string{idesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idesession.UserTable,
			Columns: []string{idesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IDESessionUpdateOne is the builder for updating a single IDESession entity.
type IDESessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IDESessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IDESessionUpdateOne) SetUpdatedAt(v time.Time) *IDESessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *IDESessionUpdateOne) SetUserID(v int64) *IDESessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillableUserID(v *int64) *IDESessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetJwtTokenHash sets the "jwt_token_hash" field.
func (_u *IDESessionUpdateOne) SetJwtTokenHash(v string) *IDESessionUpdateOne {
	_u.mutation.SetJwtTokenHash(v)
	return _u
}

// SetNillableJwtTokenHash sets the "jwt_token_hash" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillableJwtTokenHash(v *string) *IDESessionUpdateOne {
	if v != nil {
		_u.SetJwtTokenHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *IDESessionUpdateOne) SetClientID(v string) *IDESessionUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillableClientID(v *string) *IDESessionUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientVersion sets the "client_version" field.
func (_u *IDESessionUpdateOne) SetClientVersion(v string) *IDESessionUpdateOne {
	_u.mutation.SetClientVersion(v)
	return _u
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillableClientVersion(v *string) *IDESessionUpdateOne {
	if v != nil {
		_u.SetClientVersion(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *IDESessionUpdateOne) SetPlatform(v string) *IDESessionUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillablePlatform(v *string) *IDESessionUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *IDESessionUpdateOne) SetDeviceID(v string) *IDESessionUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillableDeviceID(v *string) *IDESessionUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IDESessionUpdateOne) SetExpiresAt(v time.Time) *IDESessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillableExpiresAt(v *time.Time) *IDESessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *IDESessionUpdateOne) SetLastUsedAt(v time.Time) *IDESessionUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillableLastUsedAt(v *time.Time) *IDESessionUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *IDESessionUpdateOne) SetRevoked(v bool) *IDESessionUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillableRevoked(v *bool) *IDESessionUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *IDESessionUpdateOne) SetRevokeReason(v string) *IDESessionUpdateOne {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *IDESessionUpdateOne) SetNillableRevokeReason(v *string) *IDESessionUpdateOne {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *IDESessionUpdateOne) SetUser(v *User) *IDESessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the IDESessionMutation object of the builder.
func (_u *IDESessionUpdateOne) Mutation() *IDESessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *IDESessionUpdateOne) ClearUser() *IDESessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the IDESessionUpdate builder.
func (_u *IDESessionUpdateOne) Where(ps ...predicate.IDESession) *IDESessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IDESessionUpdateOne) Select(field string, fields ...string) *IDESessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IDESession entity.
func (_u *IDESessionUpdateOne) Save(ctx context.Context) (*IDESession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IDESessionUpdateOne) SaveX(ctx context.Context) *IDESession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IDESessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IDESessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IDESessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := idesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IDESessionUpdateOne) check() error {
	if v, ok := _u.mutation.JwtTokenHash(); ok {
		if err := idesession.JwtTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "jwt_token_hash", err: fmt.Errorf(`ent: validator failed for field "IDESession.jwt_token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := idesession.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "IDESession.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientVersion(); ok {
		if err := idesession.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "IDESession.client_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := idesession.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "IDESession.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := idesession.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "IDESession.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevokeReason(); ok {
		if err := idesession.RevokeReasonValidator(v); err != nil {
			return &ValidationError{Name: "revoke_reason", err: fmt.Errorf(`ent: validator failed for field "IDESession.revoke_reason": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IDESession.user"`)
	}
	return nil
}

func (_u *IDESessionUpdateOne) sqlSave(ctx context.Context) (_node *IDESession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(idesession.Table, idesession.Columns, sqlgraph.NewFieldSpec(idesession.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IDESession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idesession.FieldID)
		for _, f := range fields {
			if !idesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(idesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.JwtTokenHash(); ok {
		_spec.SetField(idesession.FieldJwtTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(idesession.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientVersion(); ok {
		_spec.SetField(idesession.FieldClientVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(idesession.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(idesession.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(idesession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(idesession.FieldLastUsedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(idesession.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(idesession.FieldRevokeReason, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idesession.UserTable,
			Columns: []string{idesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idesession.UserTable,
			Columns: []string{idesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IDESession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
