// Code generated by ent, DO NOT EDIT.

package idesession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldUpdatedAt, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldSessionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldUserID, v))
}

// JwtTokenHash applies equality check predicate on the "jwt_token_hash" field. It's identical to JwtTokenHashEQ.
func JwtTokenHash(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldJwtTokenHash, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldClientID, v))
}

// ClientVersion applies equality check predicate on the "client_version" field. It's identical to ClientVersionEQ.
func ClientVersion(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldClientVersion, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldPlatform, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldDeviceID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldExpiresAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldLastUsedAt, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldRevoked, v))
}

// RevokeReason applies equality check predicate on the "revoke_reason" field. It's identical to RevokeReasonEQ.
func RevokeReason(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldRevokeReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldUpdatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContainsFold(FieldSessionID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldUserID, vs...))
}

// JwtTokenHashEQ applies the EQ predicate on the "jwt_token_hash" field.
func JwtTokenHashEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldJwtTokenHash, v))
}

// JwtTokenHashNEQ applies the NEQ predicate on the "jwt_token_hash" field.
func JwtTokenHashNEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldJwtTokenHash, v))
}

// JwtTokenHashIn applies the In predicate on the "jwt_token_hash" field.
func JwtTokenHashIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldJwtTokenHash, vs...))
}

// JwtTokenHashNotIn applies the NotIn predicate on the "jwt_token_hash" field.
func JwtTokenHashNotIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldJwtTokenHash, vs...))
}

// JwtTokenHashGT applies the GT predicate on the "jwt_token_hash" field.
func JwtTokenHashGT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldJwtTokenHash, v))
}

// JwtTokenHashGTE applies the GTE predicate on the "jwt_token_hash" field.
func JwtTokenHashGTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldJwtTokenHash, v))
}

// JwtTokenHashLT applies the LT predicate on the "jwt_token_hash" field.
func JwtTokenHashLT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldJwtTokenHash, v))
}

// JwtTokenHashLTE applies the LTE predicate on the "jwt_token_hash" field.
func JwtTokenHashLTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldJwtTokenHash, v))
}

// JwtTokenHashContains applies the Contains predicate on the "jwt_token_hash" field.
func JwtTokenHashContains(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContains(FieldJwtTokenHash, v))
}

// JwtTokenHashHasPrefix applies the HasPrefix predicate on the "jwt_token_hash" field.
func JwtTokenHashHasPrefix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasPrefix(FieldJwtTokenHash, v))
}

// JwtTokenHashHasSuffix applies the HasSuffix predicate on the "jwt_token_hash" field.
func JwtTokenHashHasSuffix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasSuffix(FieldJwtTokenHash, v))
}

// JwtTokenHashEqualFold applies the EqualFold predicate on the "jwt_token_hash" field.
func JwtTokenHashEqualFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEqualFold(FieldJwtTokenHash, v))
}

// JwtTokenHashContainsFold applies the ContainsFold predicate on the "jwt_token_hash" field.
func JwtTokenHashContainsFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContainsFold(FieldJwtTokenHash, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContainsFold(FieldClientID, v))
}

// ClientVersionEQ applies the EQ predicate on the "client_version" field.
func ClientVersionEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldClientVersion, v))
}

// ClientVersionNEQ applies the NEQ predicate on the "client_version" field.
func ClientVersionNEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldClientVersion, v))
}

// ClientVersionIn applies the In predicate on the "client_version" field.
func ClientVersionIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldClientVersion, vs...))
}

// ClientVersionNotIn applies the NotIn predicate on the "client_version" field.
func ClientVersionNotIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldClientVersion, vs...))
}

// ClientVersionGT applies the GT predicate on the "client_version" field.
func ClientVersionGT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldClientVersion, v))
}

// ClientVersionGTE applies the GTE predicate on the "client_version" field.
func ClientVersionGTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldClientVersion, v))
}

// ClientVersionLT applies the LT predicate on the "client_version" field.
func ClientVersionLT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldClientVersion, v))
}

// ClientVersionLTE applies the LTE predicate on the "client_version" field.
func ClientVersionLTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldClientVersion, v))
}

// ClientVersionContains applies the Contains predicate on the "client_version" field.
func ClientVersionContains(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContains(FieldClientVersion, v))
}

// ClientVersionHasPrefix applies the HasPrefix predicate on the "client_version" field.
func ClientVersionHasPrefix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasPrefix(FieldClientVersion, v))
}

// ClientVersionHasSuffix applies the HasSuffix predicate on the "client_version" field.
func ClientVersionHasSuffix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasSuffix(FieldClientVersion, v))
}

// ClientVersionEqualFold applies the EqualFold predicate on the "client_version" field.
func ClientVersionEqualFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEqualFold(FieldClientVersion, v))
}

// ClientVersionContainsFold applies the ContainsFold predicate on the "client_version" field.
func ClientVersionContainsFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContainsFold(FieldClientVersion, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContainsFold(FieldPlatform, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContainsFold(FieldDeviceID, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldExpiresAt, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldLastUsedAt, v))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldRevoked, v))
}

// RevokeReasonEQ applies the EQ predicate on the "revoke_reason" field.
func RevokeReasonEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEQ(FieldRevokeReason, v))
}

// RevokeReasonNEQ applies the NEQ predicate on the "revoke_reason" field.
func RevokeReasonNEQ(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNEQ(FieldRevokeReason, v))
}

// RevokeReasonIn applies the In predicate on the "revoke_reason" field.
func RevokeReasonIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldIn(FieldRevokeReason, vs...))
}

// RevokeReasonNotIn applies the NotIn predicate on the "revoke_reason" field.
func RevokeReasonNotIn(vs ...string) predicate.IDESession {
	return predicate.IDESession(sql.FieldNotIn(FieldRevokeReason, vs...))
}

// RevokeReasonGT applies the GT predicate on the "revoke_reason" field.
func RevokeReasonGT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGT(FieldRevokeReason, v))
}

// RevokeReasonGTE applies the GTE predicate on the "revoke_reason" field.
func RevokeReasonGTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldGTE(FieldRevokeReason, v))
}

// RevokeReasonLT applies the LT predicate on the "revoke_reason" field.
func RevokeReasonLT(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLT(FieldRevokeReason, v))
}

// RevokeReasonLTE applies the LTE predicate on the "revoke_reason" field.
func RevokeReasonLTE(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldLTE(FieldRevokeReason, v))
}

// RevokeReasonContains applies the Contains predicate on the "revoke_reason" field.
func RevokeReasonContains(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContains(FieldRevokeReason, v))
}

// RevokeReasonHasPrefix applies the HasPrefix predicate on the "revoke_reason" field.
func RevokeReasonHasPrefix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasPrefix(FieldRevokeReason, v))
}

// RevokeReasonHasSuffix applies the HasSuffix predicate on the "revoke_reason" field.
func RevokeReasonHasSuffix(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldHasSuffix(FieldRevokeReason, v))
}

// RevokeReasonEqualFold applies the EqualFold predicate on the "revoke_reason" field.
func RevokeReasonEqualFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldEqualFold(FieldRevokeReason, v))
}

// RevokeReasonContainsFold applies the ContainsFold predicate on the "revoke_reason" field.
func RevokeReasonContainsFold(v string) predicate.IDESession {
	return predicate.IDESession(sql.FieldContainsFold(FieldRevokeReason, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.IDESession {
	return predicate.IDESession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.IDESession {
	return predicate.IDESession(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IDESession) predicate.IDESession {
	return predicate.IDESession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IDESession) predicate.IDESession {
	return predicate.IDESession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IDESession) predicate.IDESession {
	return predicate.IDESession(sql.NotPredicates(p))
}
